name: kubenyancat-gha

on:
  push:
    branches:
      - 'main'
  pull_request: 
    branches:
      - 'main'

jobs:
  build-n-push-kubenyancat:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Build Docker image
        run: docker build . -t ${{ env.IMAGE_NAME }}/kube-nyan-cat:latest

      - name: Container image scan
        uses: Azure/container-scan@v0
        with:
          image-name: ${{ env.IMAGE_NAME }}/kube-nyan-cat:latest
          severity-threshold: CRITICAL
          run-quality-checks: true
        
      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}/kube-nyan-cat:latest